name: pocketflow
description: แอพจัดการหุ้น + รายงาน
publish_to: 'none'

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.8+3
  path: ^1.8.3
  fl_chart: ^0.60.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0