name: pocketflow
description: A personal finance app (PocketFlow)

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 🔥 จัดรูปแบบตัวเลข / เงิน
  intl: ^0.18.1

  # 🔥 SQLite database
  sqflite: ^2.3.0

  # 🔥 ใช้จัดการ path database
  path: ^1.9.0

  # ไอคอน iOS
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true